---
#------------------------------------------------------------------------------
# Setup pg_exporter
#------------------------------------------------------------------------------
- name: Setup pg_exporter
  tags: pg_exporter
  block:
    - name: Create /etc/pg_exporter conf dir
      file: path=/etc/pg_exporter state=directory owner=postgres group=postgres mode=0775

    - name: Copy default pg_exporter.yaml
      copy: src={{ pg_exporter_config }} dest=/etc/pg_exporter/pg_exporter.yaml owner=postgres group=postgres mode=0644

    - name: Config /etc/default/pg_exporter
      template: src=pg_exporter.j2 dest=/etc/default/pg_exporter owner=postgres group=postgres mode=0600

    - name: Config pg_exporter service unit
      template: src=pg_exporter.service.j2 dest=/usr/lib/systemd/system/pg_exporter.service

    - name: Launch pg_exporter systemd service
      systemd: name=pg_exporter state=restarted enabled=yes daemon_reload=yes

    - name: Wait for pg_exporter service online
      ignore_errors: true
      wait_for: host=127.0.0.1 port={{ pg_exporter_port }} state=started  timeout=10


#------------------------------------------------------------------------------
# Register pg_exporter
#------------------------------------------------------------------------------
- name: Setup pg_exporter
  tags: pg_exporter_register
  when: service_registry == 'consul'
  block:

    - name: Register pg-exporter consul service
      template:
        src: svc-pg-exporter.json.j2
        dest: /etc/consul.d/svc-pg-exporter.json
        owner: consul
        group: postgres
        mode: 0660

    - name: Reload pg-exporter consul service
      systemd: name=consul state=reloaded
...