---
- name: Create postgres user
  tags: pg_user
  block:
    - name: Render user {{ user.name }} creation sql
      when: pg_role == 'primary'
      tags: pg_user_config
      template: src="pg-user.sql" dest=/pg/tmp/pg-user-{{ user.name }}.sql owner={{ pg_dbsu }} group=postgres mode=0755

    - name: Execute user {{ user.name }} creation sql on primary
      tags: pg_user_create
      when: pg_role == 'primary'
      ignore_errors: true
      become_user: "{{ pg_dbsu }}"
      shell: |
        psql -p {{ pg_port }} -AXtwqf /pg/tmp/pg-user-{{ user.name }}.sql || true;
        role_exists=$(psql -p {{ pg_port }} -AXtwqc "SELECT true WHERE EXISTS(SELECT * FROM pg_authid WHERE rolname = '{{ user.name }}' LIMIT 1)")
        [[ -z "${role_exists}" ]] && exit 1 || exit 0

    - name: Add user to pgbouncer
      tags: pg_user_pgbouncer
      when: user.pgbouncer is defined and user.pgbouncer|bool
      ignore_errors: true
      become_user: "{{ pg_dbsu }}"
      shell: /pg/bin/pgbouncer-create-user '{{ user.name }}' '{% if 'password' in user %}{{ user.password }}{% else %}auto{% endif %}'

...