---
#------------------------------------------------------------------------------
# Config primary postgres node
#------------------------------------------------------------------------------

- name: Create Node
  tasks:
    debug: msg="I am in Create Node"

...